### ISSUE TITLE
Error Migration to Postgresql

### ISSUE THREAD

**Issue by Sigit-Wasis** [itstructure/laravel-rbac#3]
Start fill database...
Run all processes: migration and seeding.
   INFO  Running migrations.  

  2020_07_11_151834_create_user_role_table ............................................................................................... 10ms FAIL

   Error 

  Class "Doctrine\DBAL\Driver\AbstractPostgreSQLDriver" not found

  at vendor/laravel/framework/src/Illuminate/Database/PDO/PostgresDriver.php:8
      4▕ 
      5▕ use Doctrine\DBAL\Driver\AbstractPostgreSQLDriver;
      6▕ use Illuminate\Database\PDO\Concerns\ConnectsToDatabase;
      7▕ 
  ➜   8▕ class PostgresDriver extends AbstractPostgreSQLDriver
      9▕ {
     10▕     use ConnectsToDatabase;
     11▕ 
     12▕     /**

      +6 vendor frames 
  7   database/migrations/2020_07_11_151834_create_user_role_table.php:46
      Illuminate\Database\Connection::getDoctrineColumn("users", "id")

      +37 vendor frames 
  45  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by ankitkchetu** [comment]
run this command : composer require doctrine/dbal

**Comment by itstructure** [comment]
This issue is resolved by applying new program code line in a CreateUserRoleTable class:
`$userTablePrimaryType = Schema::getConnection()->getSchemaBuilder()->getColumnType($userModelTable, $userModelKeyName);`
