### ISSUE TITLE
Database migrations fail on vanilla Laravel 10

### ISSUE THREAD

**Issue by peterspicer-unfold** [itstructure/laravel-rbac#6]
The database migrations for this module rely on the Doctrine DBAL which isn't installed by default with Composer on Laravel 10. It might be worth flagging that as an explicit dependency for this module.

Specifically, trying to run the migration fails because it can't load `Doctrine\DBAL\Driver\AbstractMySQLDriver` which is a dependency needed to resolve the contents of getDoctrineColumn() when determining that the user id is a suitably large numeric id column.

**Comment by itstructure** [comment]
This issue is resolved by applying new program code line in a CreateUserRoleTable class:
`$userTablePrimaryType = Schema::getConnection()->getSchemaBuilder()->getColumnType($userModelTable, $userModelKeyName);`
